services:
  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=${PORT:-8000}
    volumes:
      - ./backend:/app
      - ./ml:/ml
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE=http://localhost:8000
    command: [ "npm", "run", "dev", "--", "--host" ]
