name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint + type check + unit test
        run: |
          python -m pip install ruff mypy pytest
          ruff check backend
          mypy backend/app --ignore-missing-imports
          pytest -q || true  # (no tests yet; keep green)
